### ISSUE TITLE
Likely overflow

### ISSUE THREAD

**Issue by kkartaltepe** [gegenpressing/Applied-number-theory#1]
[Line 22] (https://github.com/gegenpressing/Applied-number-theory/blob/master/IPv4_validity_checker.py#L22) Is likely to overflow. You should instead write a function that does each multiplication and then does a modulo in order to prevent overflows. It's possible python knows this is what you want to do but im pretty sure it has to be done specially (See 3^5536 is ~10^31268 >> 2^64 or whatever number of bits python might use for large integer storage).

**Comment by gegenpressing** [comment]
The overflowing was a stupid thing to have in there, and it has been fixed. A rewrite with comments is included.
